apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: coder
  labels:
    app: test
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0



  selector: 
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test   
    spec:
      containers:
      - name: test-container
        image: bitbull/webserver
        ports:
        - containerPort: 80
